api:
 -key: 2mejrqhkaqehihxju9q10zlerioxw3opdpliayaz
rss:
  api:
    -url: https://rss-2-json-api.herokuapp.com/api/v1/url?url=
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
            ddl-auto: none
#      ddl-auto: update
#          ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml